apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: chalkist
build:
  artifacts:
  - image: leffen/chalkist
    docker:
      dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
    - k8s/evelynn/chalkist-deployment.yaml
